# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # First you need to install a chromium browser in your runner
      - name: Setup Chrome
        # You may pin to the exact commit or the version.
        # uses: browser-actions/setup-chrome@4fa655aad48f56911cad16db9252399a9e592848
        uses: browser-actions/setup-chrome@v0.0.0
        with:
          # The Chromium version to install and use.
          chromium-version: # optional
      # You fetch the current ref
      - uses: actions/checkout@v2

      # Use Node version above 14.x you want to use
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
